Updates for ZMQ mode, and also to auto-load codeletSets

diff --git a/containers/Helm/templates/ue-statefulset.yaml b/containers/Helm/templates/ue-statefulset.yaml
--- a/containers/Helm/templates/ue-statefulset.yaml
+++ b/containers/Helm/templates/ue-statefulset.yaml
@@ -3,6 +3,36 @@
 {{- range $ran_name, $values := .Values.duConfigs }}
 
 ---
+
+apiVersion: v1
+kind: PersistentVolume
+metadata:
+  name: {{ $ran_name }}-zmq-trigger-pv
+spec:
+  capacity:
+    storage: 1Gi
+  accessModes:
+    - ReadWriteMany
+  persistentVolumeReclaimPolicy: Retain
+  hostPath:
+    path: {{ $.Values.zmq.triggerFiles.hostPath }}
+    type: DirectoryOrCreate
+
+---
+
+apiVersion: v1
+kind: PersistentVolumeClaim
+metadata:
+  name: {{ $ran_name }}-zmq-trigger-pvc
+spec:
+  accessModes:
+    - ReadWriteMany
+  resources:
+    requests:
+      storage: 1Gi
+
+
+---
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
@@ -27,7 +57,25 @@ spec:
         runAsUser: 0
         runAsGroup: 0
 
+      initContainers:
+
+      - name: grc-wait-for-zmq-grc-trigger
+        image: busybox:1.36
+        command:
+          - sh
+          - -c
+          - |
+            echo "Waiting for ZMQ grc trigger..."
+            until [ -f {{ $.Values.zmq.triggerFiles.mountPath }}/{{ $.Values.zmq.triggerFiles.startGRC }} ]; do
+              sleep {{ $.Values.zmq.triggerFiles.pollSeconds }}
+            done
+            echo "ZMQ GRC triggered complete."
+        volumeMounts:
+        - name: zmq-trigger
+          mountPath: {{ $.Values.zmq.triggerFiles.mountPath }}
+
       containers:
+
       - name: grc
         image: "{{ $.Values.image.srs_grc }}"
         imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
@@ -78,6 +126,11 @@ spec:
             cpu: {{ $.Values.resources.ue.limits.cpu | default "1" }}
             memory: {{ $.Values.resources.ue.limits.memory | default "1Gi" }}
 
+      volumes:
+        - name: zmq-trigger
+          persistentVolumeClaim:
+            claimName: {{ $ran_name }}-zmq-trigger-pvc
+
 
 ---
 # DNS: srs-grc-{{ $ran_name }}-zmq.<namespace>.svc.cluster.local
@@ -122,6 +175,7 @@ metadata:
   name: srs-{{ $ue_name }}-{{ $ran_name }}
   labels:
     app: srs-{{ $ue_name }}-{{ $ran_name }}
+    app.kubernetes.io/component: ue 
 spec:
   serviceName: srs-service-du-{{ $ran_name }}-{{ $ue_name }}
   selector:
@@ -131,6 +185,8 @@ spec:
     metadata:
       labels:
         app:  srs-{{ $ue_name }}-{{ $ran_name }}
+        app.kubernetes.io/component: ue
+
       # annotations:
       #   k8s.v1.cni.cncf.io/networks: '[ { "name": "srs-sriov-ue" } ]'
     spec:
@@ -140,7 +196,27 @@ spec:
         runAsUser: 0
         runAsGroup: 0
 
+
+      initContainers:
+
+      - name: ue-wait-for-zmq-connections-trigger
+        image: busybox:1.36
+        command:
+          - sh
+          - -c
+          - |
+            echo "Waiting for ZMQ connections trigger..."
+            until [ -f {{ $.Values.zmq.triggerFiles.mountPath }}/{{ $.Values.zmq.triggerFiles.startConnections }} ]; do
+              sleep {{ $.Values.zmq.triggerFiles.pollSeconds }}
+            done
+            echo "ZMQ triggered complete."
+        volumeMounts:
+        - name: zmq-trigger
+          mountPath: {{ $.Values.zmq.triggerFiles.mountPath }}
+
+
       containers:
+
       - name: ue
         image: "{{ $.Values.image.srs_ue }}"
         imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
@@ -189,7 +265,90 @@ spec:
             cpu: {{ $.Values.resources.ue.limits.cpu | default "1" }}
             memory: {{ $.Values.resources.ue.limits.memory | default "1Gi" }}
 
+      - name: traffic
+        image: "{{ $.Values.image.srs_ue }}"
+        imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
+
+        command: ["/bin/sh", "-c"]
+        args:
+          - |
+{{- if  $ue_values.iperf3.automatic }}
+            
+            set -e
+
+            echo "Waiting for ZMQ traffic trigger ({{ $.Values.zmq.triggerFiles.mountPath }}/{{ $.Values.zmq.triggerFiles.startTraffic }})..."
+            until [ -f {{ $.Values.zmq.triggerFiles.mountPath }}/{{ $.Values.zmq.triggerFiles.startTraffic }} ]; do
+              sleep {{ $.Values.zmq.triggerFiles.pollSeconds }}
+            done
+            echo "ZMQ traffic triggered complete."
+
+            # set routes and get IP
+            ./set_ue_ip_routes.sh 
+            TUN_IF="tun_srsue"
+            # Extract IP and subnet
+            UE_CIDR=$(ip -o -4 addr show dev "$TUN_IF" | awk '{print $4}')
+            echo UE_CIDR $UE_CIDR
+            if [ -z "$UE_CIDR" ]; then
+              echo "Error: $TUN_IF has no IPv4 address"
+              exit 1
+            fi
+            UE_IP=${UE_CIDR%/*}
+            echo UE_IP $UE_IP
+
+            # run iperf
+            IPERF_SERVER="{{ $ue_values.iperf3.server }}"
+            IPERF_PORT="{{ $ue_values.iperf3.port }}"
+            IPERF_BW="{{ $ue_values.iperf3.bw }}"
+            IPERF_TIME="{{ $ue_values.iperf3.duration }}"
+            IPERF_OPTS="{{ $ue_values.iperf3.cmd_options }}"
+            CMD="iperf3 -c $IPERF_SERVER -t $IPERF_TIME -p $IPERF_PORT -B $UE_IP $IPERF_OPTS -b $IPERF_BW"
+            # Add UDP options if enabled
+            if {{ $ue_values.iperf3.udp }}; then
+              CMD="$CMD -u"
+            fi
+            # Add downlink if enabled
+            if {{ $ue_values.iperf3.downlink }}; then
+              CMD="$CMD -R"
+            fi
+            echo "Will now run : $CMD"
+            $CMD
+{{- end }}
+            sleep 99999999
+
+        volumeMounts:
+        - name: zmq-trigger
+          mountPath: {{ $.Values.zmq.triggerFiles.mountPath }}
+
+        securityContext:
+          privileged: true
+          seccompProfile:
+            type: Unconfined          
+          capabilities:
+            add:
+              - NET_ADMIN
+              - NET_RAW
+              - SYS_TIME
+              - SYS_ADMIN
+              - IPC_LOCK
+              - SYS_NICE              
+        tty: true
+        stdin: true
+
+        resources:
+          requests:
+            cpu: {{ $.Values.resources.ue.requests.cpu | default "500m" }}
+            memory: {{ $.Values.resources.ue.requests.memory | default "512Mi" }}
+          limits:
+            cpu: {{ $.Values.resources.ue.limits.cpu | default "1" }}
+            memory: {{ $.Values.resources.ue.limits.memory | default "1Gi" }}
+
+      volumes:
+        - name: zmq-trigger
+          persistentVolumeClaim:
+            claimName: {{ $ran_name }}-zmq-trigger-pvc
+
 ---
+
 # DNS:  srs-{{ $ue_name }}-{{ $ran_name }}-zmq.<namespace>.svc.cluster.local
 apiVersion: v1
 kind: Service
@@ -211,8 +370,6 @@ spec:
       protocol: TCP
       port: {{ $ue_values.rx_port }}
       targetPort: {{ $ue_values.rx_port }}
-
-
 
 ---
 {{- end }}
